config/routes.rb
Rails.application.routes.draw do
  # get '', to: redirect("/#{I18n.locale}")
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  mount_roboto
  get 'sitemap.xml' => 'sitemap#sitemap', format: :xml, as: :sitemap

  if Rails.env.production?
    match "/home/deployer/apps/conde_miranda/current/invoices/invoice/:id/:basename.:extension", :controller => "admin/invoices", :action => "download", :conditions => { :method => :get }, via: :get, as: :invoice
    match "/home/deployer/apps/conde_miranda/current/invoices/rectification_invoice/:id/:basename.:extension", :controller => "admin/rectification_invoices", :action => "download", :conditions => { :method => :get }, via: :get, as: :rectification_invoice
  else
    match "#{Rails.root}/invoices/invoice/:id/:basename.:extension", :controller => "admin/invoices", :action => "download", :conditions => { :method => :get }, via: :get, as: :invoice
    match "#{Rails.root}/invoices/rectification_invoice/:id/:basename.:extension", :controller => "admin/rectification_invoices", :action => "download", :conditions => { :method => :get }, via: :get, as: :rectification_invoice
  end

  mount MailPreview => 'mail_view' if Rails.env.development?

  get '/admin', to: redirect('admin/buildings')
  root to: 'home#index'
  get '/:locale' => 'home#index', as: :root_locale

  scope :admin do
    authenticated :admin do
      root to: 'admin/buildings#index', as: :authenticated_root
    end
  end

  namespace :admin do
    resources :buildings, only: [:edit, :update, :index] do
      resources :dashboard, only: [:index] do
        get :recreate_img_versions, on: :collection
        get :export, on: :collection
      end
      # get '/dashboard' => 'dashboard#index', as: :dashboard
      resources :apartment_types, except: [:destroy, :new, :create, :show] do
        resources :prices do
          get :read_prices, on: :collection
        end
      end
      resources :apartments do
        match :change_clean, via: [:put]
        match :change_status, via: [:put]
        get :calendar, on: :member
        get :read_reservations, on: :member
        get :read_price, on: :member
        resources :disable_apartments, only: [:index] do
          put :add_disabled_dates, on: :collection
        end
      end
      resources :coupons, except: [:destroy]
      resources :calendar_dates, except: [:show]
      resources :discounts
      resources :channels, except: [:destroy]

      resources :reservations, only: [:index, :show, :new, :create, :edit, :update] do
        collection do
          # match 'search' => 'reservations#search', via: [:get, :post], as: :search
          match 'search_apartmens' => 'reservations#search_apartmens', via: [:get, :post], as: :search_apartmens
          get :index_canceled
          get :index_finished
          get :index_no_complete
        end
        get ':apartment_id/reservation' => 'reservations#reservation', on: :collection, as: :reservation
        get :copy_reservation, on: :member
        get :read_prices, on: :collection
        get :add_users, on: :member
        put :add_user, on: :member
        put :delete_user, on: :member
        get :read_reservations, on: :collection
        get :read_reservations_for_custom_calendar, on: :collection
        put :cancel, on: :member
        get ':apartment_id/summary_reservation' => 'reservations#summary_reservation', on: :collection, as: :summary_reservation
        get :new_send_confirmation
        post :send_confirmation
        # get :export, on: :collection
        resources :invoices, except: [:destroy, :show] do
          resources :rectification_invoices, only: [:new, :create]
          get :destroy_all, on: :collection
          get :new_send_invoice, on: :member
          post :send_invoice
        end
      end
      resources :clients, except: [:destroy] do
        get :export, on: :collection
        get :search, on: :collection
      end

      resources :services do
        match :change_status_services, via: [:put]
        get :read_datas, on: :member
      end
      resources :finances, only: [:index] do
        get :search_invoices, as: :search_invoices, on: :collection
        get :export_finances, on: :collection
      end
      resources :statistics, only:[:index] do
        get :search_statistics, as: :search_statistics, on: :collection
      end

      resources :invalid_dates, only: [:index, :new, :create, :edit, :update, :destroy]

      resources :ad_pdfs, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
        match :change_status, via: [:put]
      end

      resources :ad_homes, only: [:index, :edit, :update, :show] do
        match :change_status, via: [:put]
      end

      resources :config_calendars, only: [:index, :new, :create, :edit, :update, :show, :destroy]
      resources :sliders, only: [:edit, :index, :update]
      namespace :cms do
        resources :locations, only: [:edit, :index, :update]
        resources :faq_pages, only: [:edit, :update]
      end
      resources :reservation_conditions do
        get :read_percent, on: :member
        put :change_active_desactive, on: :member
      end
      resources :promotions do
        match :change_status_promotions, via: [:put]
      end
    end
    resources :admins
  end

  scope '/:locale', locale: /en|es|pt/ do
    get '/page/:id' => 'pages#show', as: :page, format: false
    get '/' => 'home#index', as: :root_public
    get 'reservation/new' => 'build#new'
    localized do
      get 'location' => 'home#location', as: :location
      get 'contact' => 'home#contact', as: :contact
      post :create_contact, to: 'home#create_contact', as: :create_contact
      get 'services' => 'home#services', as: :services
      get 'promotions' => 'home#promotions', as: :promotion
      get 'faqs' => 'home#faqs', as: :faqs
      resources :apartments, only: [:show, :index] do
        get 'search', on: :collection
        get 'get_invalid_dates', on: :collection
        get 'get_min_nights', on: :collection
      end
      resources :reservations, only: [] do
        resources :build, controller: 'build', only: [:new, :show, :update]
      end
    end
  end

  resources :calendars, only: [] do
    get :dates_conditions, on: :collection
  end

  resources :reservations, only: [] do
    post :tpv_notifier, on: :collection
    get :tpv_ok
    get :tpv_ko
    put 'check_send/:transaction_id' => 'reservations#check_send', on: :collection
    get :paypal_ok
    get :paypal_ko
  end
end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id                       :integer          not null, primary key
#  name                     :string(255)
#  surname                  :string(255)
#  nif                      :string(255)
#  email                    :string(255)
#  phone                    :string(255)
#  cif                      :string(255)
#  address                  :string(255)
#  city                     :string(255)
#  country                  :string(255)
#  business_name            :string(255)
#  type                     :string(255)
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  juvenile                 :boolean          default(FALSE)
#  agree_ads                :boolean          default(FALSE)
#  date_birth               :date
#  passport                 :string(255)
#  nationality              :string(255)
#  gender                   :string(255)
#  expedition_date_passport :date
#  expedition_date_nif      :date
#  building_id              :integer
#

class Client < ActiveRecord::Base
  attr_accessor :reservation_id, :add_renter

  has_and_belongs_to_many :reservations
  belongs_to :building

  scope :users,    -> { where(type: 'User') }
  scope :businesses, -> { where(type: 'Business')}

  validates :agree_policy_privacy, presence: true

  def is_user?
    self.type == 'User'
  end

  def is_business?
    self.type == 'Business'
  end

  def self.to_csv(options = {})
    column_names = [:name, :surname, :nif, :email, :phone]
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |cli|
        csv << cli.attributes.values_at(*column_names)
      end
    end
  end

  def get_name
    if is_business?
      self.business_name
    else
      self.name
    end
  end

  def get_identity_card
    if is_business?
      self.cif
    else
      self.nif
    end
  end

end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < Admin::BaseController

  def index
    @q = @building.clients.ransack(params[:q])

    respond_to do |format|
      format.html {
        @clients = @q.result.order(id: :desc).paginate(:page => params[:page], :per_page => 10)
      }
      format.csv {
        @clients = @q.result
        @type    = params[:type]
        render :export
      }
      format.xls {
        @clients = @q.result
        @type    = params[:type]
        render :export
      }
    end
  end

  def new
    @type = params[:type]
    @add_renter = params[:add_renter] if params[:add_renter].present?
    @reservation = params[:reservation_id].present? ? @building.reservations.actives.find(params[:reservation_id]) : nil

    if params[:type].include?("User")
      @user = @building.users.new
    else
      @business = @building.businesses.new
    end

    respond_to do |format|
      format.js
    end
  end

  def create
    if params[:user].present?
      @client = @building.users.new(permit_params_users)
      @type = 'User'
      @reservation = @building.reservations.actives.find(params[:user]['reservation_id']) if params[:user]['reservation_id'].present?
      @add_renter = params[:user]['add_renter'] if params[:user]['add_renter'].present?
    else
      @reservation = @building.reservations.actives.find(params[:business]['reservation_id']) if params[:business]['reservation_id'].present?
      @add_renter = params[:business]['add_renter'] if params[:business]['add_renter'].present?
      @add_renter = params[:business]['add_renter'] if params[:business]['add_renter'].present?
      @client = @building.businesses.new(permit_params_business)
    end

    @business = @building.businesses.all
    @users = @building.users.all

    if @client.save!
      if @add_renter.present? and @reservation.present?
        @reservation.change_rol_renter(@client)
      end
      respond_to do |format|
        format.js
      end
    end
  end

  def edit
    @reservation = params[:reservation_id].present? ? @building.reservations.actives.find(params[:reservation_id]) : nil
    @client = @building.clients.find(params[:id])
    @type = @client.type
  end

  def update
    if params[:user].present?
      @user = @building.users.find(params[:id])
      @type = 'User'
      @client = @user.update(permit_params_users)
      @reservation = @building.reservations.actives.find(params[:user]['reservation_id']) if params[:user]['reservation_id'].present?
      @users = @building.users.all
    else
      @business = @building.businesses.find(params[:id])
      @client = @business.update(permit_params_business)
      @business = @building.businesses.all
    end
  end

  def search
    @q = @building.clients.ransack(params[:q])
    @clients = @q.result.paginate(:page => params[:page], :per_page => 10)
    @reservation = Reservation.find_by(id: params[:reservation_id])
  end


  private
  def permit_params_users
    params.require(:user).permit(:type, :name, :surname, :email, :nif,
      :date_birth, :expedition_date_nif, :expedition_date_passport, :gender,
      :passport, :nationality, :phone, :reservation_id, :add_renter,
      :juvenile, :agree_ads, :agree_policy_privacy)
  end

  def permit_params_business
    params.require(:business).permit(:type, :name, :cif, :business_name,
      :address, :email, :phone, :city, :country, :reservation_id,
      :add_renter, :agree_policy_privacy, :agree_ads)
  end
end

app/helpers/admin/clients_helper.rb
module Admin::ClientsHelper
end

app/views/admin/clients/_edit_client_modal.haml
- if type == 'User'
  #myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :style => "display: none;", :tabindex => "-1"}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} x
          %h4.modal-title Editar usuario
        .modal-body
          = simple_form_for [:admin, :building, @client], url: admin_building_client_path, remote: true, :wrapper => :horizontal_form_modal , :html => {:class => 'form-horizontal edit_user'} do |f|
            = f.input :type, :input_html => {value: "User"}, as: :hidden
            - if !reservation.nil?
              = f.input :reservation_id, :input_html => {value: "#{reservation.id}"}, as: :hidden
            = f.input :name, :label => "Nombre"
            = f.input :surname, :label => "Apellidos"
            = f.input :date_birth, as: :string, :label => "Fecha de nacimiento", input_html: { class: 'date' }
            = f.input :email, :label => "Email"
            = f.input :nif, :label => "Nif"
            = f.input :expedition_date_nif, as: :string, :label => "Fecha de expedición del Nif", input_html: { class: 'date' }
            = f.input :passport, :label => "Pasaporte"
            = f.input :expedition_date_passport, as: :string, :label => "Fecha de expedición del pasaporte", input_html: { class: 'date' }
            = f.input :gender, :label => "Sexo", as: :select, :collection => ["Hombre", "Mujer"]
            = f.input :nationality, :label => "Nacionalidad"
            = f.input :phone, :label => "Teléfono"
            = f.input :juvenile, :label => "Cliente menor de edad", :wrapper => :inline_checkbox
            = f.input :agree_ads, :label => "#{I18n.t 'contact.agree_ads'}".html_safe, :wrapper => :inline_checkbox
            = f.input :agree_policy_privacy, :label => "#{I18n.t('contact.agree_policy_privacy', path_legal: page_path( I18n.locale, 'legal_notice'), path_privacy: page_path( I18n.locale, 'policy_privacy'))}".html_safe, :target => "_blank", :wrapper => :inline_checkbox, hint: I18n.t('general.policy_privacy_information_level_1')
            %br
            .text-center
              = f.submit 'Actualizar usuario', class: "btn btn-primary"
        .modal-footer
          %button.btn.btn-default.btn-sm{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} Cancelar
- else
  #myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :style => "display: none;", :tabindex => "-1"}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} x
          %h4.modal-title Editar Empresa
        .modal-body
          = simple_form_for [:admin, :building, @client], url: admin_building_client_path, remote: true, :wrapper => :horizontal_form_modal , :html => {:class => 'form-horizontal edit_business'} do |f|
            = f.input :type, :input_html => {value: "Business"}, as: :hidden
            = f.input :business_name, :label => "Razón social"
            = f.input :cif, :label => "CIF"
            = f.input :name, :label => "Persona de contacto"
            = f.input :email, :label => "Email"
            = f.input :phone, :label => "Teléfono"
            = f.input :address, :label => "Dirección"
            = f.input :city, :label => "Ciudad"
            = f.input :country
            = f.input :agree_ads, :label => "#{I18n.t 'contact.agree_ads'}".html_safe, :wrapper => :inline_checkbox
            = f.input :agree_policy_privacy, :label => "#{I18n.t('contact.agree_policy_privacy', path_legal: page_path( I18n.locale, 'legal_notice'), path_privacy: page_path( I18n.locale, 'policy_privacy'))}".html_safe, :target => "_blank", :wrapper => :inline_checkbox, hint: I18n.t('general.policy_privacy_information_level_1')
            %br
            .text-center
              = f.submit 'Actualizar empresa', class: "btn btn-primary"
        .modal-footer
          %button.btn.btn-default.btn-sm{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} Cancelar

app/views/admin/clients/_new_client_modal.html.haml
- if type == 'User'
  #myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :style => "display: none;", :tabindex => "-1"}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} x
          %h4.modal-title Nuevo Cliente
        .modal-body
          = simple_form_for [:admin, :building, @user], url: admin_building_clients_path, remote: true, :wrapper => :horizontal_form_modal , :html => {:class => 'form-horizontal'} do |f|
            = f.input :type, :input_html => {value: "User"}, as: :hidden
            - if !reservation.nil?
              = f.input :reservation_id, :input_html => {value: "#{reservation.id}"}, as: :hidden
            - if @add_renter.present?
              = f.input :add_renter, :input_html => {value: "#{@add_renter}"}, as: :hidden
            = f.input :name, :label => "Nombre"
            = f.input :surname, :label => "Apellidos"
            = f.input :date_birth, as: :string, :label => "Fecha de nacimiento", input_html: { class: 'date' }
            = f.input :email, :label => "Email"
            = f.input :nif, :label => "Nif"
            = f.input :expedition_date_nif, as: :string, :label => "Fecha de expedición del Nif", input_html: { class: 'date' }
            = f.input :passport, :label => "Pasaporte"
            = f.input :expedition_date_passport, as: :string, :label => "Fecha de expedición del pasaporte", input_html: { class: 'date' }
            = f.input :gender, :label => "Sexo", as: :select, :collection => ["Hombre", "Mujer"]
            = f.input :nationality, :label => "Nacionalidad"
            = f.input :phone, :label => "Teléfono"
            = f.input :juvenile, :label => "Cliente menor de edad", :wrapper => :inline_checkbox
            = f.input :agree_ads, :label => "#{I18n.t 'contact.agree_ads'}".html_safe, :wrapper => :inline_checkbox
            = f.input :agree_policy_privacy, :label => "#{I18n.t('contact.agree_policy_privacy', path_legal: page_path( I18n.locale, 'legal_notice'), path_privacy: page_path( I18n.locale, 'policy_privacy'))}".html_safe, :target => "_blank", :wrapper => :inline_checkbox, hint: I18n.t('general.policy_privacy_information_level_1')

            %br
            .text-center
              = f.submit 'Crear usuario', class: "btn btn-primary"
        .modal-footer
          %button.btn.btn-default.btn-sm{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} Cancelar
- else
  #myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :style => "display: none;", :tabindex => "-1"}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} x
          %h4.modal-title Nueva Empresa
        .modal-body
          = simple_form_for [:admin, :building, @business], url: admin_building_clients_path, remote: true, :wrapper => :horizontal_form_modal , :html => {:class => 'form-horizontal'} do |f|
            = f.input :type, :input_html => {value: "Business"}, as: :hidden
            = f.input :business_name, :label => "Razón social"
            = f.input :cif, :label => "CIF"
            = f.input :name, :label => "Persona de contacto"
            = f.input :email, :label => "Email"
            = f.input :phone, :label => "Teléfono"
            = f.input :address, :label => "Dirección"
            = f.input :city, :label => "Ciudad"
            = f.input :country
            - if @add_renter.present?
              = f.input :add_renter, :input_html => {value: "#{@add_renter}"}, as: :hidden
            - if !reservation.nil?
              = f.input :reservation_id, :input_html => {value: "#{reservation.id}"}, as: :hidden
            = f.input :agree_ads, :label => "#{I18n.t 'contact.agree_ads'}".html_safe, :wrapper => :inline_checkbox
            = f.input :agree_policy_privacy, :label => "#{I18n.t('contact.agree_policy_privacy', path_legal: page_path( I18n.locale, 'legal_notice'), path_privacy: page_path( I18n.locale, 'policy_privacy'))}".html_safe, :target => "_blank", :wrapper => :inline_checkbox, hint: I18n.t('general.policy_privacy_information_level_1')
            %br
            .text-center
              = f.submit 'Crear usuario', class: "btn btn-primary"
        .modal-footer
          %button.btn.btn-default.btn-sm{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} Cancelar

app/views/admin/clients/create.js.erb
<% check = @add_renter.present? %>
//caso editar reserva y agregar un usuario
<% if check and @reservation.present? %>
  $("#table_add_renter").fadeIn("slow").html('<%= escape_javascript(render 'admin/reservations/table_add_renter', clients: @clients, reservation: @reservation, building: @building) %>');
<% elsif check %>
  $("#table_add_renter").fadeIn("slow").html('<%= escape_javascript(render 'admin/reservations/table_add_renter_new', clients: @clients, building: @building, client: @client.id) %>');
<% else %>
  location.reload()
<% end %>

$("#myModal").modal('hide');

app/views/admin/clients/edit.js.erb
$("#new_client_modal").fadeIn("slow").html('<%= escape_javascript(render 'admin/clients/edit_client_modal', type: @type, reservation: @reservation) %>');
$("#myModal").modal();
$(".date").mask ("9999/99/99", {placeholder: 'yyyy/mm/dd'});
$().ready(function() {
  $('.edit_user').validate({
    rules: {
      'user[name]': 'required',
      'user[surname]': 'required',
      'user[nif]': {
        minlength: 9
      },
      'user[email]': {
        required: true,
        email: true
      },
      'user[phone]': 'required'
    },
    messages: {
      'user[name]': 'Campo obligatorio',
      'user[surname]': 'Campo obligatorio',
      'user[nif]': {
        minlength: 'Mínimo 9 caracteres. Ej. 99999999X'
      },
      'user[email]': {
        required: 'Campo obligatorio',
        email: 'Debes de introducir una dirección email correcta.'
      },
      'user[phone]': 'Campo obligatorio'

    }
  });
});

$().ready(function() {
  $('.edit_business').validate({
    rules: {
      'business[business_name]': 'required',
      'business[cif]': {
        required: true,
        minlength: 9
      },
      'business[name]' : 'required',
      'business[email]': {
        required: true,
        email: true
      },
      'business[phone]': 'required',
      'business[address]' : 'required',
      'business[city]': 'required',
      'business[country]': 'required'
    },
    messages: {
      'business[business_name]': 'Campo obligatorio',
      'business[cif]': {
        required: 'Campo obligatorio',
        minlength: 'Mínimo 9 caracteres. Ej. 99999999W'
      },
      'business[name]' : 'Campo obligatorio',
      'business[email]': {
        required: 'Campo obligatorio',
        email: 'Debes de introducir una dirección email correcta.'
      },
      'business[phone]': 'Campo obligatorio',
      'business[address]' : 'Campo obligatorio',
      'business[city]': 'Escoja la ciudad',
      'business[country]': 'Escoja un país'

    }
  });
});

app/views/admin/clients/export.csv.haml
- if @type == 'User'
  - headers = ["Nombre", 'Apellidos', 'NIF', 'Email', 'Teléfono']
  = CSV.generate_line headers
  - @clients.users.each do |cli|
    - row = [cli.name, cli.surname, cli.nif, cli.email, cli.phone]
    = CSV.generate_line(row).html_safe.strip
- else
  - headers = ["CIF", 'Razón social', 'Dirección', 'Email', 'Teléfono']
  = CSV.generate_line headers

  - @clients.businesses.each do |cli|
    - row = [cli.cif, cli.business_name, cli.address, cli.email, cli.phone]
    = CSV.generate_line(row).html_safe.strip

app/views/admin/clients/export.xls.haml
- if @type == 'User'
  .page-tables
    .table-responsive
      %table.table
        %thead
          %tr.active
            %th Nombre
            %th Apellidos
            %th NIF
            %th Email
            %th Tel&#233;fono
        %tbody
          - @clients.each do |cli|
            %tr
              %td= cli.name
              %td= cli.surname
              %td= cli.nif
              %td= cli.email
              %td= cli.phone
- else
  .page-tables
    .table-responsive
      %table.table
        %thead
          %tr.active
            %th CIF
            %th Raz&oacute;n social
            %th Direcci&oacute;n
            %th Email
            %th Tel&#233;fono
        %tbody
          - @clients.each do |cli|
            %tr
              %td= cli.cif
              %td= cli.business_name
              %td= cli.address
              %td= cli.email
              %td= cli.phone

app/views/admin/clients/index.html.haml
.single-head
  %h3.pull-left
    %i.fa.fa-users.orange
    Clientes del sistema
  .text-right
    = link_to "Añadir particular", new_admin_building_client_path(type: 'User', building_id: @building.id), :remote => true, class: "btn btn-primary"
    = link_to "Añadir empresa", new_admin_building_client_path(type: 'Business', building_id: @building.id), :remote => true, class: "btn btn-primary"
  .clearfix

.clearfix.form-search-clients
  = search_form_for [:admin, :building, @q], :html => {:class => 'form-search'} do |f|
    .col-md-3
      = f.input :name_or_surname_or_nif_or_email_or_phone_or_business_name_cont, as: :string, label: 'Buscar', required: false
    .col-md-3
      = f.input :type_eq, as: :select, collection: [[I18n.t('clients.user'), 'User'], [I18n.t('clients.business'),'Business']], label: 'Tipo de cliente', include_blank: 'Todos', required: false
    .col-md-3.actions-search
      = f.submit "Buscar", class: "btn btn-primary"
      = link_to "Limpiar", request.path, class: "btn btn-danger btn-forms"
.widget.pages-widget
  .widget-head.br-red.inline
    %h3
      %i.fa.fa-file
      Clientes
    .export
      Descargar:
      - if !params[:q] || (params[:q] && params[:q][:type_eq] == 'User')
        = link_to "CSV Usuarios", params.merge(format: :csv, type: 'User')
        |
        = link_to "Excel de Usuarios", params.merge(format: :xls, type: 'User')
        |
      - if !params[:q] || (params[:q] && params[:q][:type_eq] == 'Business')
        = link_to "CSV Empresas", params.merge(format: :csv, type: 'Business')
        |
        = link_to "Excel de empresas", params.merge(format: :xls, type: 'Business')
  .widget-body.no-padd
    .table-responsive
      %table.table.table-bordered
        %thead
          %tr
            %th ID
            %th Tipo
            %th Nombre
            %th Apellidos
            %th NIF/CIF
            %th Email
            %th Teléfono
            %th Acción
        %tbody
          - @clients.each do |client|
            %tr
              %td= client.id
              %td= I18n.t("clients.#{client.type.downcase}")
              %td= client.get_name
              %td= client.surname
              %td= client.get_identity_card
              %td= client.email
              %td= client.phone
              %td
                = link_to edit_admin_building_client_path(@building, client), class: "btn btn-xs btn-success", :remote => true do
                  %i.fa.fa-pencil
  .text-center.t-20
    = will_paginate @users, renderer: BootstrapPagination::Rails
#new_client_modal

app/views/admin/clients/new.js.erb
$("#new_client_modal").fadeIn("slow").html('<%= escape_javascript(render 'admin/clients/new_client_modal', type: @type, reservation: @reservation) %>');
$("#myModal").modal();
$(".date").mask("99/99/9999",{placeholder:"dd/mm/yyyy"});
$().ready(function() {
  $('#new_user').validate({
    rules: {
      'user[name]': 'required',
      'user[surname]': 'required',
      'user[nif]': {
        minlength: 9
      },
      'user[email]': {
        required: true,
        email: true
      },
      'user[phone]': 'required'
    },
    messages: {
      'user[name]': 'Campo obligatorio',
      'user[surname]': 'Campo obligatorio',
      'user[nif]': {
        minlength: 'Mínimo 9 caracteres. Ej. 99999999X'
      },
      'user[email]': {
        required: 'Campo obligatorio',
        email: 'Debes de introducir una dirección email correcta.'
      },
      'user[phone]': 'Campo obligatorio'

    }
  });
});

$().ready(function() {
  $('#new_business').validate({
    rules: {
      'business[business_name]': 'required',
      'business[cif]': {
        minlength: 9
      },
      'business[name]' : 'required',
      'business[email]': {
        required: true,
        email: true
      },
      'business[phone]': 'required',
      'business[address]' : 'required',
      'business[city]': 'required',
      'business[country]': 'required'
    },
    messages: {
      'business[business_name]': 'Campo obligatorio',
      'business[cif]': {
        minlength: 'Mínimo 9 caracteres. Ej. 99999999W'
      },
      'business[name]' : 'Campo obligatorio',
      'business[email]': {
        required: 'Campo obligatorio',
        email: 'Debes de introducir una dirección email correcta.'
      },
      'business[phone]': 'Campo obligatorio',
      'business[address]' : 'Campo obligatorio',
      'business[city]': 'Escoja la ciudad',
      'business[country]': 'Escoja un país'

    }
  });
});

app/views/admin/clients/search.js.erb
$("#table_add_renter").fadeIn("slow").html('<%= escape_javascript(render 'admin/reservations/table_add_renter', clients: @clients, reservation: @reservation, building: @building) %>');

app/views/admin/clients/update.js.erb
location.reload();