config/routes.rb
Rails.application.routes.draw do
  # get '', to: redirect("/#{I18n.locale}")
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  mount_roboto
  get 'sitemap.xml' => 'sitemap#sitemap', format: :xml, as: :sitemap

  if Rails.env.production?
    match "/home/deployer/apps/conde_miranda/current/invoices/invoice/:id/:basename.:extension", :controller => "admin/invoices", :action => "download", :conditions => { :method => :get }, via: :get, as: :invoice
    match "/home/deployer/apps/conde_miranda/current/invoices/rectification_invoice/:id/:basename.:extension", :controller => "admin/rectification_invoices", :action => "download", :conditions => { :method => :get }, via: :get, as: :rectification_invoice
  else
    match "#{Rails.root}/invoices/invoice/:id/:basename.:extension", :controller => "admin/invoices", :action => "download", :conditions => { :method => :get }, via: :get, as: :invoice
    match "#{Rails.root}/invoices/rectification_invoice/:id/:basename.:extension", :controller => "admin/rectification_invoices", :action => "download", :conditions => { :method => :get }, via: :get, as: :rectification_invoice
  end

  mount MailPreview => 'mail_view' if Rails.env.development?

  get '/admin', to: redirect('admin/buildings')
  root to: 'home#index'
  get '/:locale' => 'home#index', as: :root_locale

  scope :admin do
    authenticated :admin do
      root to: 'admin/buildings#index', as: :authenticated_root
    end
  end

  namespace :admin do
    resources :buildings, only: [:edit, :update, :index] do
      resources :dashboard, only: [:index] do
        get :recreate_img_versions, on: :collection
        get :export, on: :collection
      end
      # get '/dashboard' => 'dashboard#index', as: :dashboard
      resources :apartment_types, except: [:destroy, :new, :create, :show] do
        resources :prices do
          get :read_prices, on: :collection
        end
      end
      resources :apartments do
        match :change_clean, via: [:put]
        match :change_status, via: [:put]
        get :calendar, on: :member
        get :read_reservations, on: :member
        get :read_price, on: :member
        resources :disable_apartments, only: [:index] do
          put :add_disabled_dates, on: :collection
        end
      end
      resources :coupons, except: [:destroy]
      resources :calendar_dates, except: [:show]
      resources :discounts
      resources :channels, except: [:destroy]

      resources :reservations, only: [:index, :show, :new, :create, :edit, :update] do
        collection do
          # match 'search' => 'reservations#search', via: [:get, :post], as: :search
          match 'search_apartmens' => 'reservations#search_apartmens', via: [:get, :post], as: :search_apartmens
          get :index_canceled
          get :index_finished
          get :index_no_complete
        end
        get ':apartment_id/reservation' => 'reservations#reservation', on: :collection, as: :reservation
        get :copy_reservation, on: :member
        get :read_prices, on: :collection
        get :add_users, on: :member
        put :add_user, on: :member
        put :delete_user, on: :member
        get :read_reservations, on: :collection
        get :read_reservations_for_custom_calendar, on: :collection
        put :cancel, on: :member
        get ':apartment_id/summary_reservation' => 'reservations#summary_reservation', on: :collection, as: :summary_reservation
        get :new_send_confirmation
        post :send_confirmation
        # get :export, on: :collection
        resources :invoices, except: [:destroy, :show] do
          resources :rectification_invoices, only: [:new, :create]
          get :destroy_all, on: :collection
          get :new_send_invoice, on: :member
          post :send_invoice
        end
      end
      resources :clients, except: [:destroy] do
        get :export, on: :collection
        get :search, on: :collection
      end

      resources :services do
        match :change_status_services, via: [:put]
        get :read_datas, on: :member
      end
      resources :finances, only: [:index] do
        get :search_invoices, as: :search_invoices, on: :collection
        get :export_finances, on: :collection
      end
      resources :statistics, only:[:index] do
        get :search_statistics, as: :search_statistics, on: :collection
      end

      resources :invalid_dates, only: [:index, :new, :create, :edit, :update, :destroy]

      resources :ad_pdfs, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
        match :change_status, via: [:put]
      end

      resources :ad_homes, only: [:index, :edit, :update, :show] do
        match :change_status, via: [:put]
      end

      resources :config_calendars, only: [:index, :new, :create, :edit, :update, :show, :destroy]
      resources :sliders, only: [:edit, :index, :update]
      namespace :cms do
        resources :locations, only: [:edit, :index, :update]
        resources :faq_pages, only: [:edit, :update]
      end
      resources :reservation_conditions do
        get :read_percent, on: :member
        put :change_active_desactive, on: :member
      end
      resources :promotions do
        match :change_status_promotions, via: [:put]
      end
    end
    resources :admins
  end

  scope '/:locale', locale: /en|es|pt/ do
    get '/page/:id' => 'pages#show', as: :page, format: false
    get '/' => 'home#index', as: :root_public
    get 'reservation/new' => 'build#new'
    localized do
      get 'location' => 'home#location', as: :location
      get 'contact' => 'home#contact', as: :contact
      post :create_contact, to: 'home#create_contact', as: :create_contact
      get 'services' => 'home#services', as: :services
      get 'promotions' => 'home#promotions', as: :promotion
      get 'faqs' => 'home#faqs', as: :faqs
      resources :apartments, only: [:show, :index] do
        get 'search', on: :collection
        get 'get_invalid_dates', on: :collection
        get 'get_min_nights', on: :collection
      end
      resources :reservations, only: [] do
        resources :build, controller: 'build', only: [:new, :show, :update]
      end
    end
  end

  resources :calendars, only: [] do
    get :dates_conditions, on: :collection
  end

  resources :reservations, only: [] do
    post :tpv_notifier, on: :collection
    get :tpv_ok
    get :tpv_ko
    put 'check_send/:transaction_id' => 'reservations#check_send', on: :collection
    get :paypal_ok
    get :paypal_ko
  end
end

app/models/service.rb
# == Schema Information
#
# Table name: services
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  price        :float(24)
#  active       :boolean          default(FALSE)
#  building_id  :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  published    :boolean
#  unique_price :float(24)
#  tax          :integer
#  rest_one_day :boolean          default(FALSE)
#

class Service < ActiveRecord::Base
	DESCRIPTION = ["Servicio opcional", "Optional service"]
	belongs_to :building
	has_many :coupon_types, dependent: :nullify
	translates :name, :description
	globalize_accessors :locales => [:en, :es, :pt], :attributes => [:name, :description]

	validates :name_es, :name_en, presence: true
	validates :price, presence: true, :if => :unique_no_present?
	validates :tax, presence: true

	scope :for_reservation, -> {where('published = true and active=true')}

	def unique_no_present?
		!self.unique_price.present?
	end

	def label_description
		self.unique_price? ? "#{self.name} (#{self.price}€)" : "#{self.name} (#{self.price}€/dia)"
	end

	# def label_description
	# 	"#{self.name}"
	# end

	def unique_price?
		self.unique_price.present?
	end

end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < Admin::BaseController
  def index
    @services = @building.services.all
  end

  def edit
    @service = @building.services.find(params[:id])
  end

  def update
    respond_to do |format|
      @service = @building.services.find(params[:id])
      if @service.update(permit_params)
        format.html { redirect_to admin_building_services_path(@building), notice: 'El servicio ha sido actualizado correctamente' }
      else
        format.html { render :edit }
      end
    end

    
  end

  def new
    @service = @building.services.new
  end

  def create
    @service = @building.services.new(permit_params)

    if @service.save
      # format.html { redirect_to admin_building_coupons_path(@building), notice: 'Has creado un nuevo cupón' }
      flash[:success] = "Servicio creado satisfactoriamente"
      redirect_to admin_building_services_path
    else
      flash[:error] = "Algo ha ido mal, por favor, inténtalo de nuevo"
      render :new
    end
  end

  def show
    @service = @building.services.find(params[:id])
  end

  def destroy
  end

  def change_status_services
    @service = @building.services.find(params[:service_id])
    
    if @service.active == true
      @service.update(:active => false)
    else
      @service.update(:active => true)
    end
    render :nothing => true
  end

  def read_datas
    @service = @building.services.find(params[:id])
    respond_to do |format|
      format.json{ render :json => @service }
    end
  end


  private
  def permit_params
    params.require(:service).permit(:name_es, :name_en, :name_pt, :price, :unique_price, :active, :published, :tax,
      :description_es, :description_en, :description_pt, :rest_one_day)
  end
end

app/helpers/admin/services_helper.rb
module Admin::ServicesHelper
end

app/views/admin/services/_form.html.haml
= simple_form_for [:admin, @building, @service], :wrapper => :horizontal_form, :html => {:class => 'form-horizontal'} do |f|
	
	= f.input :name_es, :label => "Nombre es"
	= f.input :name_en, :label => "Nombre en"
	= f.input :name_pt, :label => "Nombre pt"
	= f.input :price, :label => "Precio por día", :hint => "Este campo sólo será obligatorio en caso de no establecer el precio único."
	= f.input :unique_price, :label => "Precio único"
	= f.input :tax, :label => "Impuesto", as: :select, collection: 1..100
	= f.input :description_es, as: :text, :label => "Descripción es"
	= f.input :description_en, as: :text, :label => "Descripción en"
	= f.input :description_pt, as: :text, :label => "Descripción pt"
	= f.input :published, :label => "Aparece en el formulario de reserva", :wrapper => :horizontal_radio_and_checkboxes, :item_wrapper_class => 'col-sm-4'
	= f.input :rest_one_day, :label => "Restar un día del total de noches", :wrapper => :horizontal_radio_and_checkboxes, :item_wrapper_class => 'col-sm-4'


	.form-actions
		= f.button :submit, "Guardar", class: "btn btn-primary"

app/views/admin/services/edit.html.haml
.single-head
  %h3.pull-left
    %i.fa.fa-plus-circle.orange
    = "Editando servicio #{@service.name}"
  .clearfix

= render 'form'

app/views/admin/services/index.html.haml
.single-head
  %h3.pull-left
    %i.fa.fa-plus-circle.orange
    Administrar Servicios
  = link_to "Crear servicio", new_admin_building_service_path, class: "pull-right btn btn-primary btn-create"
  
  .clearfix

.page-tables
  .table-responsive
    %table.table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%", id: "data-table"}
      %thead
        %tr
          %th Nombre
          %th Precio por día
          %th Precio único
          %th Impuesto
          %th Estado
          %th Acciones
      %tbody
        - @services.each do |servi|
          %tr
            %td= servi.name
            - if servi.price.present?
              %td
                = servi.price
                €
            - else
              %td= "-"
            - if servi.unique_price.present?
              %td
                = servi.unique_price
                €
            - else
              %td= "-"
            %td.center= tax(servi.tax)
            %td.center
              %input.cleaning{:checked => servi.active? == true ? true : false, :name => "my-checkbox2", :type => "checkbox", "data-on-text": "Activo", "data-off-text": "Inactivo", "data-on-color": "success", "data-off-color": "warning", :id => servi.id, "data_building"=> @building.id}/
            %td
              = link_to  edit_admin_building_service_path(@building ,servi), class: "btn btn-xs btn-success" do
                %i.fa.fa-pencil
              = link_to  admin_building_service_path(@building, servi), class: "btn btn-xs btn-info" do
                %i.fa.fa-eye

app/views/admin/services/new.html.haml
.single-head
  %h3.pull-left
    %i.fa.fa-plus-circle.orange
    = "Crear Servicio"
  .clearfix

= render 'form'

app/views/admin/services/show.html.haml
.single-head
  %h3.pull-left
    %i.fa.fa-plus-circle.orange
    = "Servicio #{@service.name}"
  .clearfix

.row
  .col-md-12.col-lg-12
    %table.table.table-user-information
      %tbody
        %tr
          %td 
            %strong Nombre es:
          %td= @service.name_es
        %tr
          %td 
            %strong Nombre en:
          %td= @service.name_en
        %tr
          %td 
            %strong Precio:
          %td
            = @service.price
            €
        - if @service.unique_price.present?
          %tr
            %td 
              %strong Precio único:
            %td= @service.unique_price
        %tr
          %td 
            %strong Aparece en el formulario de reserva:
          - if @service.published == true
            %td= "Sí"
          - else
            %td= "No"
        / %tr
        /   %td 
        /     %strong Estado:
        /   %td= @service.active