config/routes.rb
Rails.application.routes.draw do
  # get '', to: redirect("/#{I18n.locale}")
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  mount_roboto
  get 'sitemap.xml' => 'sitemap#sitemap', format: :xml, as: :sitemap

  if Rails.env.production?
    match "/home/deployer/apps/conde_miranda/current/invoices/invoice/:id/:basename.:extension", :controller => "admin/invoices", :action => "download", :conditions => { :method => :get }, via: :get, as: :invoice
    match "/home/deployer/apps/conde_miranda/current/invoices/rectification_invoice/:id/:basename.:extension", :controller => "admin/rectification_invoices", :action => "download", :conditions => { :method => :get }, via: :get, as: :rectification_invoice
  else
    match "#{Rails.root}/invoices/invoice/:id/:basename.:extension", :controller => "admin/invoices", :action => "download", :conditions => { :method => :get }, via: :get, as: :invoice
    match "#{Rails.root}/invoices/rectification_invoice/:id/:basename.:extension", :controller => "admin/rectification_invoices", :action => "download", :conditions => { :method => :get }, via: :get, as: :rectification_invoice
  end

  mount MailPreview => 'mail_view' if Rails.env.development?

  get '/admin', to: redirect('admin/buildings')
  root to: 'home#index'
  get '/:locale' => 'home#index', as: :root_locale

  scope :admin do
    authenticated :admin do
      root to: 'admin/buildings#index', as: :authenticated_root
    end
  end

  namespace :admin do
    resources :buildings, only: [:edit, :update, :index] do
      resources :dashboard, only: [:index] do
        get :recreate_img_versions, on: :collection
        get :export, on: :collection
      end
      # get '/dashboard' => 'dashboard#index', as: :dashboard
      resources :apartment_types, except: [:destroy, :new, :create, :show] do
        resources :prices do
          get :read_prices, on: :collection
        end
      end
      resources :apartments do
        match :change_clean, via: [:put]
        match :change_status, via: [:put]
        get :calendar, on: :member
        get :read_reservations, on: :member
        get :read_price, on: :member
        resources :disable_apartments, only: [:index] do
          put :add_disabled_dates, on: :collection
        end
      end
      resources :coupons, except: [:destroy]
      resources :calendar_dates, except: [:show]
      resources :discounts
      resources :channels, except: [:destroy]

      resources :reservations, only: [:index, :show, :new, :create, :edit, :update] do
        collection do
          # match 'search' => 'reservations#search', via: [:get, :post], as: :search
          match 'search_apartmens' => 'reservations#search_apartmens', via: [:get, :post], as: :search_apartmens
          get :index_canceled
          get :index_finished
          get :index_no_complete
        end
        get ':apartment_id/reservation' => 'reservations#reservation', on: :collection, as: :reservation
        get :copy_reservation, on: :member
        get :read_prices, on: :collection
        get :add_users, on: :member
        put :add_user, on: :member
        put :delete_user, on: :member
        get :read_reservations, on: :collection
        get :read_reservations_for_custom_calendar, on: :collection
        put :cancel, on: :member
        get ':apartment_id/summary_reservation' => 'reservations#summary_reservation', on: :collection, as: :summary_reservation
        get :new_send_confirmation
        post :send_confirmation
        # get :export, on: :collection
        resources :invoices, except: [:destroy, :show] do
          resources :rectification_invoices, only: [:new, :create]
          get :destroy_all, on: :collection
          get :new_send_invoice, on: :member
          post :send_invoice
        end
      end
      resources :clients, except: [:destroy] do
        get :export, on: :collection
        get :search, on: :collection
      end

      resources :services do
        match :change_status_services, via: [:put]
        get :read_datas, on: :member
      end
      resources :finances, only: [:index] do
        get :search_invoices, as: :search_invoices, on: :collection
        get :export_finances, on: :collection
      end
      resources :statistics, only:[:index] do
        get :search_statistics, as: :search_statistics, on: :collection
      end

      resources :invalid_dates, only: [:index, :new, :create, :edit, :update, :destroy]

      resources :ad_pdfs, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
        match :change_status, via: [:put]
      end

      resources :ad_homes, only: [:index, :edit, :update, :show] do
        match :change_status, via: [:put]
      end

      resources :config_calendars, only: [:index, :new, :create, :edit, :update, :show, :destroy]
      resources :sliders, only: [:edit, :index, :update]
      namespace :cms do
        resources :locations, only: [:edit, :index, :update]
        resources :faq_pages, only: [:edit, :update]
      end
      resources :reservation_conditions do
        get :read_percent, on: :member
        put :change_active_desactive, on: :member
      end
      resources :promotions do
        match :change_status_promotions, via: [:put]
      end
    end
    resources :admins
  end

  scope '/:locale', locale: /en|es|pt/ do
    get '/page/:id' => 'pages#show', as: :page, format: false
    get '/' => 'home#index', as: :root_public
    get 'reservation/new' => 'build#new'
    localized do
      get 'location' => 'home#location', as: :location
      get 'contact' => 'home#contact', as: :contact
      post :create_contact, to: 'home#create_contact', as: :create_contact
      get 'services' => 'home#services', as: :services
      get 'promotions' => 'home#promotions', as: :promotion
      get 'faqs' => 'home#faqs', as: :faqs
      resources :apartments, only: [:show, :index] do
        get 'search', on: :collection
        get 'get_invalid_dates', on: :collection
        get 'get_min_nights', on: :collection
      end
      resources :reservations, only: [] do
        resources :build, controller: 'build', only: [:new, :show, :update]
      end
    end
  end

  resources :calendars, only: [] do
    get :dates_conditions, on: :collection
  end

  resources :reservations, only: [] do
    post :tpv_notifier, on: :collection
    get :tpv_ok
    get :tpv_ko
    put 'check_send/:transaction_id' => 'reservations#check_send', on: :collection
    get :paypal_ok
    get :paypal_ko
  end
end

app/models/invoice.rb
# == Schema Information
#
# Table name: invoices
#
#  id             :integer          not null, primary key
#  reservation_id :integer
#  number         :string(255)
#  date           :datetime
#  customer_id    :integer
#  customer_type  :string(255)
#  notes          :text(65535)
#  total          :float(24)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  attachment     :string(255)
#

class Invoice < ActiveRecord::Base
  before_destroy :delete_relationship
  attr_accessor :billing_address, :customer_invoice
  by_star_field :date
  mount_uploader :attachment, AttachmentUploader

  belongs_to :reservation
  belongs_to :customer, polymorphic: true
  belongs_to :billing_address
  has_many :billings, -> {where invoice_id: nil}, :through => :reservation
  has_many :billings_in, :class_name => 'Billing'
  has_many :invoice_items, :dependent => :destroy
  has_one :rectification_invoice, :dependent => :destroy

  scope :with_no_rectification, -> { includes(:rectification_invoice).where( :rectification_invoices => { :id => nil } )}

  accepts_nested_attributes_for :billings

  def total_no_taxes
    self.invoice_items.present? ? self.invoice_items.sum(:total_price_base).round(2) : 0
  end

  def taxes
    self.invoice_items.present? ? self.invoice_items.sum(:total_vat).round(2) : 0
  end

  def total
    self.invoice_items.present? ? self.invoice_items.sum(:total_price).round(2) : 0
  end

  def self.get_next_number_invoice(building)
    prefix         = building.invoice_address.prefix_invoice_number
    number_invoice = building.invoices.any? ? building.invoices.last.number.split('-') : ["#{prefix}000", '16']
    number         = number_invoice[0].scan(/\d+/).first
    year           = Date.today.year.to_s.last(2)

    num =
      if year != number_invoice[1]
        "#{prefix}1-#{year}"
      else
        "#{prefix}#{number.to_i + 1}-#{year}"
      end

    num
  end

  def get_customer_name
    if self.customer.class.name == "User"
      name = customer.name
      cif = customer.nif.presence || customer.passport.presence
    else
      name = customer.business_name
      cif = customer.cif
    end
    "#{name} - #{cif}"
  end

  def get_customer_datas
    if self.customer.class.name == "User"
      name_customer = [customer.name, customer.try(:surname)].join(" ")
      cif = customer.nif.presence || customer.passport.presence
    else
      name_customer = customer.business_name
      cif = customer.cif
    end

    return name_customer, cif
  end

  def get_payment_types
    self.reservation.payment_summaries.pluck(:method).try(:join, ',')
  end

  def has_rectification?
    false
  end

  def delete_relationship
    self.billings_in.each do |b|
      b.update_attribute(:invoice_id, nil)
    end
  end

  def self.destroy_all_invoices
    Billing.all.each do |b|
      if b.invoice_id.present?
        b.invoice = nil
        b.save!
      end
    end

    self.all.each do |inv|
      if inv.billings_in.present?
        inv.billings_in.delete_all
      end
      inv.destroy
    end
  end
end

app/controllers/admin/invoices_controller.rb
class Admin::InvoicesController < Admin::BaseController
  before_action :set_building_and_reservation, except: :download
  before_action :set_invoice, only: [:new_send_invoice]

  def index
    @invoices = @reservation.invoices
  end

  def new
    @invoice = @reservation.invoices.new
    @total = @reservation.billings.no_invoice.sum(:amount)
    unless @reservation.billing_address
      renter = @reservation.get_renter
      @reservation.build_billing_address(
        country: renter.country,
        address: renter.address,
        city: renter.city,
        nationality: renter.nationality
      )
    end
  end

  def create
    ActiveRecord::Base.transaction do
      billing_address = @reservation.billing_address || @reservation.create_billing_address
      billing_address.update(permit_params[:billing_address])

      client   = @building.clients.find(permit_params[:customer_invoice])
      @invoice = @reservation.invoices.new(permit_params)

      @invoice.billing_address = billing_address
      @invoice.customer_id     = client.id
      @invoice.customer_type   = client.type
      @invoice.number          = Invoice.get_next_number_invoice(@building)

      if permit_params_billing.present? and @reservation.update(permit_params_billing) and @invoice.save!
        @reservation.billings.no_invoice.each do |b|
          b.update_attribute(:invoice_id, @invoice.id)
        end
        @invoice.update_attribute(:total, @invoice.total)

        # creamos los items de la factura
        @invoice.billings_in.each do |item|
          vat      = item.amount - (item.amount / ((item.tax/100.0) + 1))
          vat_unit = item.price - (item.price / ((item.tax/100.0) + 1))
          concept  = item.service.present? ? "#{item.service.name_es}/#{item.service.name_en}" : item.reservation.apartments.first.name

          description =
            if item.description.blank?
              item.concept.include?("service") ? "Servicio/Service" : "Apto./Apartment"
            else
              item.description
            end

          @invoice.invoice_items.create(
            concept: concept, description: description, vat_type: item.tax, unit: item.night,
            unit_price_base: (item.price - vat_unit), unit_price: item.price,
            total_price_base: (item.amount - vat),
            total_price: item.amount, unit_vat: vat_unit , total_vat: vat
          )
        end

        #crear pdf y guardar
        pdf = InvoicePdf.new(@invoice, @reservation)
        tempfile = Tempfile.new(["#{@invoice.id}", '.pdf'], Rails.root.join('tmp'))
        tempfile.binmode
        tempfile.write pdf.render
        tempfile.close
        @invoice.attachment = tempfile
        @invoice.save!
        # Close the tempfile and delete it
        tempfile.unlink

        redirect_to admin_building_reservation_invoices_path(@building,@reservation)
      else
        flash[:alert] = "No se pude crear una factura sin items o con items en blanco"
        @total = @reservation.billings.no_invoice.sum(:amount)
        render :new
      end
    end
  end

  def download
    path = invoice_path(params[:id], params[:basename], params[:extension])
    if params[:action_pdf].present?
      send_file path, :x_sendfile=>true, :disposition  => "inline"
    else
      send_file path, :x_sendfile=>true
    end
  end

  def destroy_all
    @building.invoices.destroy_all_invoices
    redirect_to :back
  end

  def new_send_invoice
    @send_invoice_form = Invoices::SendInvoiceForm.new
    @candidate_emails  = @send_invoice_form.candidate_emails(
      reservation: @reservation,
      invoice: @invoice
    )
  end

  def send_invoice
    @send_invoice_form = Invoices::SendInvoiceForm.new(permit_params_send_invoice)
    @invoice           = @send_invoice_form.invoice
    if @send_invoice_form.submit!
      flash[:success] = "Correo enviado a #{@send_invoice_form.email} con la factura adjunta #{@invoice.number}"
    else
      @candidate_emails  = @send_invoice_form.candidate_emails(
        reservation: @reservation,
        invoice: @invoice
      )

      render :new_send_invoice
    end
  end

  private
  def set_building_and_reservation
    @reservation = @building.reservations.find(params[:reservation_id])
  end

  def set_invoice
    @invoice =
      if params[:invoice_type] == 'invoice'
        @reservation.invoices.find(params[:id])
      else
        @reservation.rectification_invoices.find(params[:id])
      end
  end

  def permit_params
    params.require(:invoice).permit(:date, :customer_invoice, billing_address: [:address, :address_1, :country, :city, :zip_code, :nationality])
  end

  def permit_params_billing
    params.require(:invoice).permit(billings_attributes:[:id, :_destroy, :description, :price, :night, :tax, :amount, :service_id, :concept])
  end

  def permit_params_send_invoice
    params.require(:invoices_send_invoice_form).permit(:email, :invoice_id, :invoice_type, :message)
  end
end

app/helpers/admin/invoices_helper.rb
module Admin::InvoicesHelper
	def tax(tax)
		"#{tax}%"
	end
end

app/views/admin/invoices/_form.html.haml
#building_id.hidden= @building.id
#nights.hidden= num_night(@reservation.start_date.to_date, @reservation.end_date.to_date)
= simple_nested_form_for [:admin, @building, @reservation, @invoice], :wrapper => :horizontal_form_invoice , :html => {:class => 'form-horizontal'} do |f|

  .row
    .col-lg-6
      / = f.input :number, :label => "Num factura", :input_html => {class: "form-control input-sm"}
      = f.input :date, as: :date_picker, :label => "Fecha:", :input_html => {class: "form-control", value: Date.today.strftime('%d/%m/%Y')}
      = f.input :customer_invoice, as: :select, collection: @reservation.clients_reservations.map{|c| c.user.present? ? [c.user.datas_invoice, c.user.id] : [c.business.datas_invoice, c.business.id]}, :label => "Cliente", :input_html => {class: "form-control input-sm"}, :include_blank => false
      #user_data

    .col-lg-6
      = f.fields_for @reservation.billing_address, :wrapper => :horizontal_form_invoice , :html => {:class => 'form-horizontal'} do |b|
        = b.input :address, input_html: { class: "form-control input-sm" }, label: "Dirección"
        = b.input :address_1, input_html: { class: "form-control input-sm" }, label: "Dirección 2"
        /= b.input :country, :input_html => {class: "form-control input-sm"}, :label => "País"
        = b.input :city, input_html: { class: "form-control input-sm" }, label: "Ciudad"
        = b.input :zip_code, input_html: { class: "form-control input-sm" }, label: "Código postal"
        = b.input :nationality, input_html: { class: "form-control input-sm" }, label: "País"

  .row
    .col-md-12
      %hr/
      .table-responsive
        %table.table.table-invoice.table-bordered
          %thead
            %tr
              %th
              %th Concepto
              %TH Descripción
              %th Precio
              %th Noches / Unidades
              %th Tax
              %th Total
          %tbody

            = f.simple_fields_for :billings, :wrapper => false do |b|

              %tr.fields
                %td= b.link_to_remove "X", class: "btn btn-xs btn-danger"
                %td
                  - if b.object.service.present?
                    = b.object.service.name
                  - elsif b.object.concept == "apartment"
                    = b.object.reservation.apartments.first.name
                  - else
                    = b.association :service, as: :select, label_method: :label_description, :label => false, collection: @building.services
                %td= b.input :description, :label => false
                %td
                  = b.input :price, :label => false, :input_html => {class: "price"}
                %td
                  = b.input :night, :label => false, :input_html => {class: "night"}
                %td
                  = b.input :tax, as: :select, collection: 0..100, :label => false, :input_html => {class: "tax"}
                %td
                  = b.input :amount, :label => false, :input_html => {class: "amount"}
                  = b.input :concept, as: :hidden, :input_html => {value: "service"} if b.object.new_record?
            %tr
              %td= f.link_to_add "Añadir", :billings, :class => "btn btn-mini", id: 'add_line_item'

  .row.text-center
    .col-md-offset-4.col-sm-offset-4.col-md-4.col-sm-4
      .well.br-green
        %h4 PRECIO FINAL
        %h2.price_with_tax= normal_price(@total)


  = f.submit "Crear factura", class: "btn btn-primarty",  data: {confirm: "Si creas la factura no podrás modificarla, ¿estas seguro?"}

app/views/admin/invoices/_new_send_invoice.html.haml
#modalSendInvoice.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :style => "display: none;", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} x
        %h4.modal-title= "Enviar factura #{invoice.number}"
      .modal-body
        = bootstrap_flash
        = simple_form_for send_invoice_form, url: admin_building_reservation_invoice_send_invoice_path(building, reservation, invoice), remote: true, :html => {:class => 'form-horizontal'} do |f|
          .col-lg-12
            = f.input :email
            = f.input :message, as: :text
            = f.input :invoice_id, as: :hidden, input_html: { value: invoice.id }
            = f.input :invoice_type, as: :hidden, input_html: { value: invoice.class.name }
          .col-lg-12
            %div Emails asociados a la reserva:
            - if candidate_emails.any?
              - candidate_emails.each do |email|
                %div= email
            - else
              No hay mail asociado a la reserva.
          .col-lg-12
            .text-center
              = f.submit 'Enviar mail', class: "btn btn-primary"
          .clearfix
      .modal-footer
        %button.btn.btn-default.btn-sm{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} Cancelar

app/views/admin/invoices/index.html.haml
.single-head
  %h3.pull-left
    %i.fa.fa-file-pdf-o.orange
    = "Facturas reserva - #{@reservation.reference}"
  = link_to "Crear Factura", new_admin_building_reservation_invoice_path, class: "pull-right btn btn-primary btn-create"
  .clearfix

.page-tables
  .table-responsive#client-table2
    %table.table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%", id: "data-table"}
      %thead
        %tr
          %th Número
          %th Titular
          %th Fecha creación
          %th Factura
          %th Factura rectificativa
      %tbody
        - @invoices.each do |invoice|
          %tr
            %td= invoice.number
            %td= invoice.get_customer_name
            %td= invoice.created_at.strftime('%d/%m/%Y')
            %td
              = link_to "Ver", invoice_path(invoice.number, File.basename(invoice.attachment.url), :extension => "pdf", :action_pdf => "show"), target: '_blank'
              |
              = link_to "Descargar", invoice_path(invoice.number, File.basename(invoice.attachment.url), :extension => "pdf")
              |
              = link_to "Enviar", new_send_invoice_admin_building_reservation_invoice_path(@building, @reservation, invoice, invoice_type: :invoice), remote: true
            %td
              - if invoice.rectification_invoice.present?
                = link_to "Ver", rectification_invoice_path(invoice.rectification_invoice.number, File.basename(invoice.rectification_invoice.attachment.url), :extension => "pdf", :action_pdf => "show"), target: '_blank'
                |
                = link_to "Descargar", rectification_invoice_path(invoice.rectification_invoice.number, File.basename(invoice.rectification_invoice.attachment.url), :extension => "pdf")
                |
                = link_to "Enviar", new_send_invoice_admin_building_reservation_invoice_path(@building, @reservation, invoice.rectification_invoice, invoice_type: :rectification), remote: true
              - else
                = link_to "Crear factura rectificativa", new_admin_building_reservation_invoice_rectification_invoice_path(@building, @reservation, invoice), :remote => :true

.hidden= link_to "Borrar todas las facturas", destroy_all_admin_building_reservation_invoices_path(@building, @reservation)

#modal-rectification-invoice
#modal

app/views/admin/invoices/new.html.haml
.single-head
  %h3.pull-left
    %i.fa.fa-desktop.orange
    = "Crear factura reserva #{@reservation.reference}"
  
  .clearfix

= render 'form'

app/views/admin/invoices/new_send_invoice.js.erb
$(".modal-backdrop.fade.in").remove();
$("#modal").fadeIn("slow").html('<%= escape_javascript(render 'admin/invoices/new_send_invoice', building: @building, reservation: @reservation, invoice: @invoice, send_invoice_form: @send_invoice_form, candidate_emails: @candidate_emails ) %>');
$("#modalSendInvoice").modal();

app/views/admin/invoices/send_invoice.js.erb
$("#modalSendInvoice").modal('hide');
location.reload();