config/routes.rb
Rails.application.routes.draw do
  # get '', to: redirect("/#{I18n.locale}")
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  mount_roboto
  get 'sitemap.xml' => 'sitemap#sitemap', format: :xml, as: :sitemap

  if Rails.env.production?
    match "/home/deployer/apps/conde_miranda/current/invoices/invoice/:id/:basename.:extension", :controller => "admin/invoices", :action => "download", :conditions => { :method => :get }, via: :get, as: :invoice
    match "/home/deployer/apps/conde_miranda/current/invoices/rectification_invoice/:id/:basename.:extension", :controller => "admin/rectification_invoices", :action => "download", :conditions => { :method => :get }, via: :get, as: :rectification_invoice
  else
    match "#{Rails.root}/invoices/invoice/:id/:basename.:extension", :controller => "admin/invoices", :action => "download", :conditions => { :method => :get }, via: :get, as: :invoice
    match "#{Rails.root}/invoices/rectification_invoice/:id/:basename.:extension", :controller => "admin/rectification_invoices", :action => "download", :conditions => { :method => :get }, via: :get, as: :rectification_invoice
  end

  mount MailPreview => 'mail_view' if Rails.env.development?

  get '/admin', to: redirect('admin/buildings')
  root to: 'home#index'
  get '/:locale' => 'home#index', as: :root_locale

  scope :admin do
    authenticated :admin do
      root to: 'admin/buildings#index', as: :authenticated_root
    end
  end

  namespace :admin do
    resources :buildings, only: [:edit, :update, :index] do
      resources :dashboard, only: [:index] do
        get :recreate_img_versions, on: :collection
        get :export, on: :collection
      end
      # get '/dashboard' => 'dashboard#index', as: :dashboard
      resources :apartment_types, except: [:destroy, :new, :create, :show] do
        resources :prices do
          get :read_prices, on: :collection
        end
      end
      resources :apartments do
        match :change_clean, via: [:put]
        match :change_status, via: [:put]
        get :calendar, on: :member
        get :read_reservations, on: :member
        get :read_price, on: :member
        resources :disable_apartments, only: [:index] do
          put :add_disabled_dates, on: :collection
        end
      end
      resources :coupons, except: [:destroy]
      resources :calendar_dates, except: [:show]
      resources :discounts
      resources :channels, except: [:destroy]

      resources :reservations, only: [:index, :show, :new, :create, :edit, :update] do
        collection do
          # match 'search' => 'reservations#search', via: [:get, :post], as: :search
          match 'search_apartmens' => 'reservations#search_apartmens', via: [:get, :post], as: :search_apartmens
          get :index_canceled
          get :index_finished
          get :index_no_complete
        end
        get ':apartment_id/reservation' => 'reservations#reservation', on: :collection, as: :reservation
        get :copy_reservation, on: :member
        get :read_prices, on: :collection
        get :add_users, on: :member
        put :add_user, on: :member
        put :delete_user, on: :member
        get :read_reservations, on: :collection
        get :read_reservations_for_custom_calendar, on: :collection
        put :cancel, on: :member
        get ':apartment_id/summary_reservation' => 'reservations#summary_reservation', on: :collection, as: :summary_reservation
        get :new_send_confirmation
        post :send_confirmation
        # get :export, on: :collection
        resources :invoices, except: [:destroy, :show] do
          resources :rectification_invoices, only: [:new, :create]
          get :destroy_all, on: :collection
          get :new_send_invoice, on: :member
          post :send_invoice
        end
      end
      resources :clients, except: [:destroy] do
        get :export, on: :collection
        get :search, on: :collection
      end

      resources :services do
        match :change_status_services, via: [:put]
        get :read_datas, on: :member
      end
      resources :finances, only: [:index] do
        get :search_invoices, as: :search_invoices, on: :collection
        get :export_finances, on: :collection
      end
      resources :statistics, only:[:index] do
        get :search_statistics, as: :search_statistics, on: :collection
      end

      resources :invalid_dates, only: [:index, :new, :create, :edit, :update, :destroy]

      resources :ad_pdfs, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
        match :change_status, via: [:put]
      end

      resources :ad_homes, only: [:index, :edit, :update, :show] do
        match :change_status, via: [:put]
      end

      resources :config_calendars, only: [:index, :new, :create, :edit, :update, :show, :destroy]
      resources :sliders, only: [:edit, :index, :update]
      namespace :cms do
        resources :locations, only: [:edit, :index, :update]
        resources :faq_pages, only: [:edit, :update]
      end
      resources :reservation_conditions do
        get :read_percent, on: :member
        put :change_active_desactive, on: :member
      end
      resources :promotions do
        match :change_status_promotions, via: [:put]
      end
    end
    resources :admins
  end

  scope '/:locale', locale: /en|es|pt/ do
    get '/page/:id' => 'pages#show', as: :page, format: false
    get '/' => 'home#index', as: :root_public
    get 'reservation/new' => 'build#new'
    localized do
      get 'location' => 'home#location', as: :location
      get 'contact' => 'home#contact', as: :contact
      post :create_contact, to: 'home#create_contact', as: :create_contact
      get 'services' => 'home#services', as: :services
      get 'promotions' => 'home#promotions', as: :promotion
      get 'faqs' => 'home#faqs', as: :faqs
      resources :apartments, only: [:show, :index] do
        get 'search', on: :collection
        get 'get_invalid_dates', on: :collection
        get 'get_min_nights', on: :collection
      end
      resources :reservations, only: [] do
        resources :build, controller: 'build', only: [:new, :show, :update]
      end
    end
  end

  resources :calendars, only: [] do
    get :dates_conditions, on: :collection
  end

  resources :reservations, only: [] do
    post :tpv_notifier, on: :collection
    get :tpv_ok
    get :tpv_ko
    put 'check_send/:transaction_id' => 'reservations#check_send', on: :collection
    get :paypal_ok
    get :paypal_ko
  end
end

app/models/apartment_type.rb
# == Schema Information
#
# Table name: apartment_types
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  building_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class ApartmentType < ActiveRecord::Base

	belongs_to :building
	has_many :apartments
	has_many :prices, dependent: :destroy

	def apartment_type_select
		"#{self.name}"
	end

	def lowest_price
		min_price = self.prices.after(Time.now, field: :night).order(price: :asc).first
		min_price.try(:price)
	end

end

app/controllers/admin/apartments_controller.rb
class Admin::ApartmentsController < Admin::BaseController

  before_action :set_admin_apartment, only: [:show, :edit, :update, :destroy]

  # GET /admin/apartments
  # GET /admin/apartments.json
  def index
    @admin_apartments = @building.apartments.includes(:apartment_type).no_deleted
    respond_to do |format|
      format.html
      format.csv #{send_data @admin_apartments.to_csv}
      format.xls #{send_data @admin_apartments.to_csv(col_sep: "\t")}
    end
  end

  # GET /admin/apartments/1
  # GET /admin/apartments/1.json
  def show
    @admin_apartment = @building.apartments.includes(:apartment_type, :translations, :photos => [:translations]).find(params[:id])
  end

  # GET /admin/apartments/new
  def new
    @admin_apartment = @building.apartments.new
  end

  # GET /admin/apartments/1/edit
  def edit
  end

  # POST /admin/apartments
  # POST /admin/apartments.json
  def create
    @admin_apartment = @building.apartments.new(admin_apartment_params)

    respond_to do |format|
      if @admin_apartment.save
        format.html { redirect_to admin_building_apartments_path(@building), notice: 'Has creado un nuevo apartamento' }
        format.json { render :show, status: :created, location: @admin_apartment }
      else
        format.html { render :new }
        format.json { render json: @admin_apartment.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /admin/apartments/1
  # PATCH/PUT /admin/apartments/1.json
  def update
      if @admin_apartment.update(admin_apartment_params)
        redirect_to admin_building_apartments_path(@building), notice: 'El apartamento ha sido actualizado correctamente'
      else
        render :edit 
      end
  end

  def change_clean
    @apartment = Apartment.find_by_id(params[:apartment_id])
    if @apartment.cleaned?
      @apartment.dirty!
    else
      @apartment.clean!
    end
    render :nothing => true
  end

  def change_status
    @apartment = Apartment.find_by_id(params[:apartment_id])
    if @apartment.active == true
      @apartment.update(:active => false)
    else
      @apartment.update(:active => true)
    end
    render :nothing => true
  end

  def calendar
    @apartment = @building.apartments.no_deleted.find(params[:id])
  end

  def read_reservations
    @apartment = @building.apartments.no_deleted.find(params[:id])
    @reservations = @apartment.reservations.actives
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @reservations.as_json({:individual => true})}
    end
  end

  def read_price
    apartment = @building.apartments.no_deleted.find(params[:id])
    price = apartment.get_price(params[:start_date].to_date, params[:end_date].to_date)
    
    respond_to do |format|
      format.json{ render :json => price }
    end
  end

  def destroy
    @apartment = @building.apartments.no_deleted.find(params[:id])
    @apartment.update(deleted_at: DateTime.now)
    redirect_to admin_building_apartments_path(@building)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_apartment
      @admin_apartment = @building.apartments.includes(:apartment_type).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_apartment_params
      params.require(:apartment).permit(:ref, :name, :living_room, :num_persons, :num_bedrooms, 
        :bed_kind, :badroom, :double_couch, :description_es, :description_en, :description_pt, 
        :apartment_type_id, :metatitle, :metadescription, :metakey, equipment_ids: [], 
        photos_attributes: [:id, :caption_es, :caption_en, :caption_pt, :_destroy, :picture, :accordion_pic]
      )
    end
end

app/controllers/apartments_controller.rb
class ApartmentsController < BasePublicController
  def index
    @apartments = @building.apartments
                           .includes(:apartment_type, :photos, :translations)
                           .no_deleted
                           .active
  end

  def search
    parse_dates_searches

    service_search_apts = Apartments::Search.new(
      current_user: current_user,
      building: @building,
      start_date: @start_date,
      end_date: @end_date,
      exclude_inactives: true
    )

    if service_search_apts.valid? && service_search_apts.call
      apts = service_search_apts.apartments_available

      @coupon = @building.coupons.find_by_code(permit_params_search[:code]) unless permit_params_search[:code].blank?
      coupon_service = CouponService.new(@coupon, @start_date, @end_date)
      days_before = (@start_date - Date.today).to_i

      if !@coupon
        @nights              = (@end_date - @start_date).to_i
        discount_nights      = @building.discounts.check_if_discount_avaliable(@nights)
        discount_beforehand  = @building.discounts.check_if_days_before_discount_available(days_before)
        @applicable_discount = discount_nights || discount_beforehand
      elsif @coupon && !coupon_service.coupon_is_on_time_and_conditions?
        @error_coupon = 'coupon_no_valid'
      end

      reservation_service = ReservationService.new(
        @coupon,
        @building,
        @start_date,
        @end_date,
        discount_nights,
        discount_beforehand
      )

      @apartments = []
      apts.each do |apartment|
        price = apartment.get_price(@start_date, @end_date).try(:to_f)
        if !price.nil? && !price.zero?
          @apartments << [apartment, reservation_service.get_prices_for_apartment_and_conditions(apartment, price)]
        end
      end

      render :search
    else
      flash[:danger] = I18n.t 'reservation.error.invalid_dates'
      redirect_to :back
    end
  end

  def show
    @apartment = @building.apartments.includes(:photos => [:translations]).no_deleted.find(params[:id])
    @from_reservation = params[:apartment_id].present? and params[:coupon].present? and params[:end_date].present? and params[:start_date].present? and params[:price].present?
  end

  def get_invalid_dates
    @invalid_dates = @building.invalid_dates.all.map(&:date)
    respond_to do |format|
      format.json { render json: @invalid_dates }
    end
  end

  def get_min_nights
    respond_to do |format|
      if (min_nights = @building.config_calendars.first)
        format.json { render json: min_nights.nights }
      else
        format.json { render json: 1 }
      end
    end
  end

  private

  def parse_dates_searches
    if permit_params_search[:dates]
      dates       = permit_params_search[:dates].tr(' ','').split('-')
      @start_date = dates[0].try(:to_date)
      @end_date   = dates[1].try(:to_date)
    else
      @start_date = permit_params_search[:check_in].try(:to_date)
      @end_date   = permit_params_search[:check_out].try(:to_date)
    end
  end

  def permit_params_search
    params.permit(:dates, :guests, :code, :check_in, :check_out)
  end
end

app/helpers/admin/apartments_helper.rb
module Admin::ApartmentsHelper
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/views/apartments/_search_form.html.haml
= form_tag(search_apartments_path, method: "get", class: "barra-busqueda") do
  %span.error-barra-reserva-no-blank
    = I18n.t 'apartments.apartment_search.errors.must_choose_date'
  %h3.titulo-barra-busqueda
    = I18n.t 'apartments.apartment_search.booking_online'
  %div{:class => "bloque-barra-reserva br-calendario"}
    %div{:class => "barra-reserva-item bri-check"}
      - start_date = @start_date.try(:strftime, "%d-%m-%Y") || params.try(:[], :check_in)
      %input#check-in{:type => "text",:name => "check_in",:placeholder =>   "#{I18n.t 'apartments.apartment_search.start'}", value: start_date}
    %div{:class => "barra-reserva-item bri-check"}
      - end_date = @end_date.try(:strftime, "%d-%m-%Y") || params.try(:[], :check_out)
      %input#check-out{:type => "text",:name => "check_out",:placeholder => "#{I18n.t 'apartments.apartment_search.end'}", value: end_date}
    .clearfix
  %div{:class => "bloque-barra-reserva br-personas"}
    %div{:class => "barra-reserva-item"}
      %select#personas{:name => "guests"}
        - (1..6).each do |v|
          %option{:value => v, selected: params[:guests].try(:to_i) == v}
            = v
    .clearfix
  .forclear
  %div{:class => "bloque-barra-reserva br-add"}
    %div{:class => "barra-reserva-item"}
      %input#promo{:type => "text",:name => "code",:placeholder => "#{I18n.t 'apartments.apartment_search.coupon'}", value: ("#{@coupon.code}" if @coupon.present? and !@coupon.nil?)}
  %div{:class => "bloque-barra-reserva br-add"}
    %div{:class => "barra-reserva-item"}
      %input#reservar-barra-busqueda{:type => "submit",:name => "search",:value => "#{I18n.t 'apartments.apartment_search.book_button'}"}
  .clearfix
.text-center
  .caja-ventajas
    %h1
      = I18n.t 'apartments.apartment_search.booking_advantage_bar'
    %h1.ventajas
      = I18n.t('apartments.apartment_search.advantage_bar')
      //= link_to (I18n.t 'apartments.apartment_search.advantage_bar'), "#my-modal", id: "modal-advantage", data: {toggle: "modal", target: "#myModal"}, id: "modal-advantage"

app/views/apartments/index.html.haml
.contenedor-interno-general
  = render 'apartments/search_form'
  = render 'home/modal_advantage'
  %br
  %table
    %thead
      %tr
        %td.datos-mobile= "#{I18n.t 'apartments.apartment_search.apartment'}"
        %td.datos-desktop= "#{I18n.t 'apartments.apartment_search.rooms'}"
        %td.datos-desktop= "#{I18n.t 'apartments.apartment_search.pax'}"
        %td.datos-desktop= "#{I18n.t 'apartments.apartment_search.price'}"
        %td.datos-desktop= "#{I18n.t 'apartments.apartment_search.booking'}"
    %tbody
      - @apartments.each do |apart|
        - if lowest_price = ApartmentService.new(apart).get_from_min_price
          %tr
            %td.datos-mobile
              - if apart.photos.present?
                = link_to apartment_path(apart), class: "contenedor-imagen-results" do
                  = image_tag apart.photos.no_accordion.first.picture.url(:thumbnail), alt: apart.photos.no_accordion.first.caption
                  %h3.titulo-apartamento-busqueda= apart.name
              - else
                = link_to "ver",  apartment_path(apart), class: "contenedor-imagen-results"
              %div.datos-completos-mobile
                %p
                  %span.resaltado-numeros= apart.num_bedrooms
                  = "#{I18n.t 'apartments.text.room', :count => apart.num_bedrooms}"
                %p
                  %span.resaltado-numeros= apart.num_persons
                  pax
                %p
                  %span.resaltado-numeros
                    = "#{I18n.t 'apartments.text.from'} #{lowest_price.try(:floor)}"
                  = "€ / #{I18n.t 'apartments.text.night'}"
                = link_to "#{I18n.t 'apartments.index.see_apartment'}", apartment_path(apart), class: "enlace-reserva"
            %td.datos-desktop= apart.num_bedrooms
            %td.datos-desktop= apart.num_persons
            %td.datos-desktop
              = "#{I18n.t 'apartments.text.from'} #{lowest_price.try(:floor)} € / #{I18n.t 'apartments.text.night'}"
            %td.datos-desktop
              = link_to "#{I18n.t 'apartments.index.see_apartment'}", apartment_path(apart), class: "enlace-reserva"

app/views/apartments/search.html.haml
.contenedor-interno-general{"onunload" => ""}
  <input type="hidden" id="refresh" value="no">
  - if @start_date.present? and @end_date.present?
    = render 'apartments/search_form'
    = render 'home/modal_advantage'
    .result_search_for
      - if @error_coupon.present?
        .alert.alert-warning.alert-dismissible{:role => "alert"}
          %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          - if @error_coupon.include?('coupon_invalid_num_nights')
            = I18n.t "apartments.apartment_search.errors.#{@error_coupon}", min_night: @coupon.minimum_nights, max_night: @coupon.maximum_nights
          - else
            = I18n.t "apartments.apartment_search.errors.#{@error_coupon}"
      %div= I18n.t 'apartments.apartment_search.result_search'
      %div
        = "#{I18n.t 'apartments.apartment_search.start'}: #{@start_date.strftime('%d/%m/%y')} | #{I18n.t 'apartments.apartment_search.end'}: #{@end_date.strftime('%d/%m/%y')} | #{I18n.t 'apartments.apartment_search.pax'}: #{params[:guests]} "
        = "| #{I18n.t 'apartments.apartment_search.coupon'}: #{@coupon.code} (-#{@coupon.discount}%)" if @coupon.present? and !@coupon.nil? and !@error_coupon.present?
      %div{style: "color: #bd1a63"}
        =raw "#{@coupon.description}" if @coupon.present?
        =raw "#{@applicable_discount.description}" if @applicable_discount.present? and !@applicable_discount.nil?
        = @errors_coupon
  - if @apartments.empty?
    %div.no-result= t 'apartments.apartment_search.no_results_html'
  - else
    - @apartments.each_with_index do |apart, index|
      %table
        %thead
          %tr
            %td.datos-mobile{class: ("no-visible" if !index.zero?), style: "width: 33%"}= "#{I18n.t 'apartments.apartment_search.apartment'}"
            %td.datos-desktop{class: ("no-visible" if !index.zero?), style: "width: 33%"}= "#{I18n.t 'apartments.apartment_search.rooms'}"
            %td.datos-desktop{class: ("no-visible" if !index.zero?), style: "width: 20%"}= "#{I18n.t 'apartments.apartment_search.pax'}"
            %td.datos-desktop{class: "no-visible", style: "display: none;"}= "#{I18n.t 'apartments.apartment_search.price'}"
            %td.datos-desktop{class: "no-visible" , style: "width: 20%"}= "#{I18n.t 'apartments.apartment_search.booking'}"
        %tbody.initial
          %tr.mobile
            %td.datos-mobile
              - if apart[0].photos.present?
                = link_to apartment_path(apart[0], apartment_id: apart[0].id, start_date: @start_date, end_date: @end_date, coupon: (@coupon.present? and !@error_coupon.present? ? @coupon.code : ""), price: apart[1], price_discount: apart[2], nights: @nights), class: "contenedor-imagen-results" do
                  = image_tag apart[0].photos.no_accordion.first.picture.url(:thumbnail), alt: apart[0].photos.no_accordion.first.caption
                  %h3.titulo-apartamento-busqueda= apart[0].name
              - else
                = link_to "ver",  apartment_path(apart[0], apartment_id: apart[0].id, start_date: @start_date, end_date: @end_date, coupon: (@coupon.present? and !@error_coupon.present? ? @coupon.code : ""), price: apart[1], price_discount: apart[2], nights: @nights), class: "contenedor-imagen-results"
              %div.datos-completos-mobile
                %p
                  %span.resaltado-numeros= apart[0].num_bedrooms
                  = "#{I18n.t 'apartments.text.room', :count => apart[0].num_bedrooms}"
                %p
                  %span.resaltado-numeros= apart[0].num_persons
                  pax
                %table
                  %tbody
                    %tr
                      %th{:colspan => "4"}
                    - apart[1].each do |condition|
                      %tr
                        %td
                          %span{style: "margin-right: 7px;"}= condition[:title]
                          - if condition[:description].present?
                            %i.fa.fa-info-circle{"data-placement" => "top", "data-toggle" => "tooltip", "data-html"=>"true", :title => "#{condition[:description].html_safe}"}
                        %td
                          - if !condition[:discount].zero?
                            %span.before= = condition[:normal_price]
                          = condition[:discount_price]
                        %td
                          = radio_button("condition", "#{apart[0].slug}-mobile", "#{condition[:id]}", class: "reservation-condition-radio-mobile")
                    %tr
                      %th{:colspan => "4"}= link_to "#{I18n.t 'apartments.apartment_search.book_button'}", reservation_new_path(apartment_id: apart[0].id, start_date: @start_date, end_date: @end_date, coupon: (@coupon.present? and !@error_coupon.present? ? @coupon.code : ""), condition_reservation: @building.reservation_conditions.default.id), class: "enlace-reserva", disabled: true, "data-placement": "top", title: I18n.t('apartments.apartment_search.cannot_reservation_without_condition_selected')
            %td.datos-desktop= apart[0].num_bedrooms
            %td.datos-desktop= apart[0].num_persons
            %table.datos-desktop
              %tbody
                %tr
                  %th{:colspan => "4"}
                  %th{:rowspan => "4", style: "text-align: right;"}
                    = link_to "#{I18n.t 'apartments.apartment_search.book_button'}", reservation_new_path(apartment_id: apart[0].id, start_date: @start_date, end_date: @end_date, coupon: (@coupon.present? and !@error_coupon.present? ? @coupon.code : ""), condition_reservation: @building.reservation_conditions.default.id), class: "enlace-reserva tooltip-manual", disabled: true, "data-placement": "top", title: I18n.t('apartments.apartment_search.cannot_reservation_without_condition_selected')
                    = params[:condition_reservation]
                - apart[1].each do |condition|
                  %tr
                    %td{style: "width: 64%; text-align: right;padding-right: 15%;"}
                      %span{style: "margin-right: 7px;"}= condition[:title]
                      - if condition[:description].present?
                        %i.fa.fa-info-circle{"data-placement" => "top", "data-toggle" => "tooltip", "data-html"=>"true", :title => "#{condition[:description].html_safe}"}
                    %td
                      - if !condition[:discount].zero?
                        %span.before= condition[:normal_price]
                      = condition[:discount_price]
                    %td
                      = radio_button("condition", "#{apart[0].slug}", "#{condition[:id]}", class: "reservation-condition-radio")


:javascript
  $(document).ready(function(e) {
    var $input = $('#refresh');
    $input.val() == 'yes' ? location.reload(true) : $input.val('yes');
  });

app/views/apartments/show.html.haml
- title @apartment.metatitle.blank? ? "Apartamento Madrid - #{@apartment.name}" : "#{@apartment.metatitle}"
- description @apartment.metadescription.blank? ? "Apartamento Madrid - #{@apartment.name}" : "#{@apartment.metadescription}"
- keywords @apartment.metakey.blank? ? "alquiler Madrid, hospedaje Madrid" : "#{@apartment.metakey}"
.contenedor-interno-individual
  #carousel-example-generic.carousel.slide{"data-ride" => "carousel"}
    %ol.carousel-indicators
      - @apartment.photos.no_accordion.each_with_index do |page, index|
        %li{"data-slide-to" => "#{index}", "data-target" => "#carousel-example-generic", class: ("active" if index == 0)}
    .carousel-inner
      - @apartment.photos.no_accordion.each_with_index do |pic, index|
        .item{:class => ("active" if index == 0)}
          = image_tag pic.picture, height: "600", width: "2000", alt: pic.caption
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev"><span class="fa fa-chevron-left"></span></a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next"><span class="fa fa-chevron-right"></span></a>
  .contenedor-datos-individuales
    .contenedor-datos-individuales-interno
      %h1.nombre-apartamento-individual= @apartment.name
      %p.info-apartamento-individual
        %span.sub-info-individual= "#{@apartment.num_bedrooms} #{I18n.t 'apartments.text.room', :count => @apartment.num_bedrooms}" "|"
        %span.sub-info-individual= "#{@apartment.num_persons} pax |"
        %span.sub-info-individual= "#{I18n.t 'apartments.text.from'}  #{ApartmentService.new(@apartment).get_from_min_price.try(:floor)}€ / #{I18n.t 'apartments.text.night'}"

      / - if @from_reservation
      /   = link_to "#{I18n.t 'apartments.apartment_search.book_button'}", reservation_new_path(apartment_id: params[:apartment_id], start_date: params[:start_date], end_date: params[:end_date], coupon: params[:coupon], condition_reservation: @building.reservation_conditions.first.id), class: "enlace-reserva enlace-reserva-individual"
      /   .clearfix
      / - else
      = link_to "#{I18n.t 'apartments.apartment_search.book_button'}", apartments_path, class: "enlace-reserva enlace-reserva-individual"
      .clearfix
  .contenedor-datos-individuales-interno
    .contenedor-descripcion= @apartment.description.html_safe
    .contenedor-descripcion
      %ul.contenedor-featuretes
        - @apartment.equipments.each do |eq|
          %li.featurete-contenida= I18n.t "apartments.equipments.#{eq.key}"
        .clearfix